services:
  - type: web
    name: slideai-ppt
    runtime: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && python main.py
    envVars:
      - key: OPENAI_BASE_URL
        value: https://compass.llm.shopee.io/compass-api/v1
      - key: OPENAI_API_KEY
        value: 48e923df74cb1351f6d7aa0fd174c346f0c437a2a5c5d63986e6ca91077c812d
      - key: OPENAI_MODEL
        value: gpt-4o
      - key: PORT
        value: 8000
